### ISSUE TITLE
Věk lidí v grafu Aktuální proočkovanost

### ISSUE THREAD

**Issue by michalblaha** [tomkmec/yacd#5]
V dostupných open datech je věk pouze jako interval (30-35, 45-49). Ale graf "Aktuální proočkovanost" (mimochodem skvělá vizualizace!) je po jednotlivých letech. 

Jak je to řešeno? Aproximace na jednotlivé ročníky?

**Comment by tomkmec** [comment]
Každou kategorii beru jako kastlik do kterého zprava doleva a pak nahoru
přidávám. Takže až bude 2000 naočkovaných 0-17, bude jeden čtvereček na 17,
pak na 16,...
Zkusím tak dát nějaké swimlajny jak to bude vypadat. A taky mi teď docvaklo
že tam mám nejspíš chybu a 80+ jsou ukázané nesprávně. Večer na to hodím
oko jestli bude čas a síla.
A dík!

Dne čt 18. 3. 2021 17:56 uživatel Michal Blaha ***@***.***>
napsal:

**Comment by tomkmec** [comment]
Zaokrouhlování bylo špatně. Teď by to mělo být ok. Ale pozor, je to magie a zvýšení počtu očkovaných ve věkové kategorii o 2000 nemusí díky zaokrouhlovacím kompenzacím rozsvítit další čtvereček. 
Mezi kategorie jsem přidal malé mezery a vypadá to líp, s trochou důvtipu už jde vidět jak se jednotlivé kategorie plní.
